### ISSUE TITLE
Using a branch other than "master" breaks the Spanish translation link on npmjs.com

### ISSUE THREAD

**Issue by binki** [zkat/cacache#103] opened 2017-06-17 19:46 UTC
https://www.npmjs.com/package/cacache

If I click “español” I get a 404.

**Comment by zkat** [comment] 2017-06-17 20:23
I think this will be fixed as soon as a new version gets published, since I'm pretty sure the changes needed to marky-markdown to get this to work have already landed

**Comment by zkat** [comment] 2017-06-17 20:42
Confirmed. It should work now, after I published a new version. Cheers.

**Closed as completed by zkat** 2017-06-17 20:42 UTC
